#! /usr/bin/env python3
from __future__ import annotations

import sys

from pypechain.main import main

if __name__ == "__main__":
    # TODO: add a bash script to make this easier, i.e. ./pypechain './abis', './build'
    # TODO: make this installable so that other packages can use the command line tool
    if len(sys.argv) == 3:
        main(sys.argv[1], sys.argv[2])
    elif len(sys.argv) == 4:
        main(sys.argv[1], sys.argv[2], int(sys.argv[3]))
    else:
        print(
            "Usage: python script_name.py <path_to_abi_file> <output_dir> <line_length>"
        )
