name: Check Diff

on:
  workflow_call:
    inputs:
      file_path:
        description: File to check for version change
        required: true
        type: string
    outputs:
      version_changed:
        description: true if the version line in the file has changed
        value: ${{ jobs.check.outputs.version_changed }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for version changes
        id: check
        run: |
          VERSION_LINE_BASE=$(git show ${{ github.event.pull_request.base.sha }}:${{ inputs.file_path }} | grep '^version =')
          VERSION_LINE_HEAD=$(grep '^version =' ${{ inputs.file_path }})

          if [ "$VERSION_LINE_BASE" != "$VERSION_LINE_HEAD" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi
